# Generated by Django 5.2.4 on 2025-07-11 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('course_code', models.CharField(help_text='Course code, e.g., CS101. Used by students to find the exam.', max_length=100)),
                ('start_time', models.DateTimeField(help_text='When the exam becomes available for students to start.')),
                ('end_time', models.DateTimeField(help_text='When the exam is no longer available for students to start.')),
                ('duration_minutes', models.PositiveIntegerField(help_text='Duration of the exam in minutes once a student starts.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False, help_text='Lecturer activates this to make it visible/takeable by students (within start/end time).')),
                ('lecturer_user', models.ForeignKey(limit_choices_to={'is_staff': False, 'is_superuser': False}, on_delete=django.db.models.deletion.CASCADE, related_name='exams_managed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exam',
                'verbose_name_plural': 'Exams',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(default='essay', help_text='Type of question, e.g., essay, multiple_choice.', max_length=50)),
                ('marks', models.PositiveIntegerField(default=1, help_text='Marks allocated for this question.')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='lecturer_portal.exam')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
    ]
