# Generated by Django 5.2.4 on 2025-07-11 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturer_portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='lecturer_answer_key',
            field=models.TextField(blank=True, help_text='Correct answer for fill-in-the-blanks or keywords/ideal answer for essays.', null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='marks',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(help_text="For 'Fill in the Blanks', use underscores for blank spaces, e.g., 'The capital of France is __Paris__.')"),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('fill_in_the_blanks', 'Fill in the Blanks'), ('essay', 'Essay / Short Answer')], default='multiple_choice', max_length=20),
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='lecturer_portal.question')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_correct', True)), fields=('question',), name='unique_correct_option_per_question')],
            },
        ),
    ]
