# Generated by Django 5.2.4 on 2025-07-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturer_portal', '0002_question_lecturer_answer_key_alter_question_marks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='case_sensitive',
            field=models.BooleanField(default=False, help_text='Check this if the fill-in-the-blanks answer requires case-sensitive matching.'),
        ),
    ]
