# Generated by Django 5.2.4 on 2025-07-11 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LecturerCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this code will no longer be valid for initial activation/login.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Overall status of this code/lecturer slot.')),
                ('associated_admin', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_lecturer_codes', to=settings.AUTH_USER_MODEL)),
                ('lecturer_user', models.OneToOneField(blank=True, limit_choices_to={'is_staff': False, 'is_superuser': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_code', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lecturer Access Code',
                'verbose_name_plural': 'Lecturer Access Codes',
            },
        ),
    ]
