# Generated by Django 5.2.4 on 2025-07-11 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lecturer_portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matric_number', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, help_text='Actual time student started this attempt.')),
                ('submission_time', models.DateTimeField(blank=True, help_text='Actual time student submitted.', null=True)),
                ('score', models.IntegerField(blank=True, help_text='Total score for this attempt.', null=True)),
                ('grace_login_granted', models.BooleanField(default=False, help_text='Set by lecturer to allow re-entry or late start.')),
                ('attempt_deadline', models.DateTimeField(blank=True, help_text='Calculated deadline for this specific attempt.', null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='lecturer_portal.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to='student_portal.student')),
            ],
            options={
                'verbose_name': 'Exam Attempt',
                'verbose_name_plural': 'Exam Attempts',
                'unique_together': {('student', 'exam')},
            },
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True, null=True)),
                ('marks_awarded', models.IntegerField(default=0, help_text='Marks awarded for this specific answer.')),
                ('exam_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='student_portal.examattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='lecturer_portal.question')),
            ],
            options={
                'verbose_name': 'Student Answer',
                'verbose_name_plural': 'Student Answers',
                'unique_together': {('exam_attempt', 'question')},
            },
        ),
    ]
