# Generated by Django 5.2.4 on 2025-07-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='cheating_attempts',
            field=models.PositiveIntegerField(default=0, help_text='Number of times the student has attempted to cheat.'),
        ),
    ]
